title: RadioNugget
description: "Explorez le monde fascinant des radiofréquences et des satellites avec des explications simples et claires"
profile_img: "/assets/img/profile.webp"
url: "https://radionugget.com"

github_username: nxugget
linkedin_username: alexiw
instagram_username: radionugget
twitter_username: nxugget_

data-repo: "nxugget/radionugget"
data-repo-id: "R_kgDOL8zpzg"
data-category: "Q&A"
data-category-id: "DIC_kwDOL8zpzs4CfbXu"

goatcounter_code: radionugget

giscus_repo: "nxugget/radionugget"
giscus_repoId: "R_kgDOL8zpzg"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDOL8zpzs4CfbXu"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/
  - vendor

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
  math_engine: mathjax

incremental: true