title: RadioNugget
description: "Explorez le monde fascinant des radiofréquences et des satellites avec des explications simples et claires"
logo_img: "/assets/img/favicon.ico"
profile_img: "/assets/img/profile.webp"

github_username: nxugget
linkedin_username: alexiswahib
instagram_username: radionugget

giscus_repo: "radionugget/radionugget"
giscus_repoId: "R_kgDOL8zpzg"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDOL8zpzs4CfbXu"
goatcounter_code: radionugget

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
  math_engine: mathjax
