title: RadioNugget
description: "Explorez le monde fascinant des radiofréquences et des satellites avec des explications simples et claires"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/profile.webp"

# Social Links
github_username: nxugget
linkedin_username: alexiswahib
instagram_username: radionugget

# External API
giscus_repo: "radionugget/radionugget"
giscus_repoId: "R_kgDOL8zpzg"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDOL8zpzs4CfbXu"
goatcounter_code: radionugget

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
  math_engine: mathjax
